services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projector-ui-production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - projector-ui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=projector-ui"
      - "environment=production"

networks:
  projector-ui-network:
    driver: bridge